// <auto-generated />
namespace CasoUno.Principal.Front.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class InicializacionV1_DB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InicializacionV1_DB));
        
        string IMigrationMetadata.Id
        {
            get { return "202606251901548_InicializacionV1_DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
